### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by josephgupkim** [rcao137/jammming#3]
I hope for future projects that you’ll add some comments to your code base as I believe they can improve its overall legibility. You can utilize comments by providing insight into why and how you chose to write your code a certain way. This will allow readers/developers to approach your code with an aided mindset that could be efficient how they look at your code. You can also use comments to section of certain portions and label them accordingly. However you choose to use them, I hope you’ll try making a habit of it in the future!

**Comment by rcao137** [comment]
I have added more comments in unit 4.
